import type { Metadata } from 'next';
import '../../assets/styles/globals.css';
import { ThemeProvider } from '../../shared/modules/components/theme/theme-provider.component';
import { Toaster } from 'sonner';
import { SidebarProvider } from '@/src/shared/modules/components/ui/sidebar';
import { AppSidebar } from '@/src/shared/modules/components/navigation/app-sidebar.component';
import NavbarComponent from '@/src/shared/modules/components/navigation/navbar.component';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <AppSidebar />
            <div className="flex flex-col w-full">
              <NavbarComponent />
              <main className="flex-1 px-6 py-4">{children}</main>
            </div>
          </SidebarProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
