import type { Metadata } from 'next';
import '../../../assets/styles/globals.css';
import { Urbanist } from 'next/font/google';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'Pronto Afeto',
  description: 'Generated by create next app',
};

const montserrat = Urbanist({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '700'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={montserrat.className}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
