import type { Metadata } from 'next';
import '../../assets/styles/globals.css';
import Image from 'next/image';
import { ThemeProvider } from '@/src/shared/modules/components/theme/theme-provider.component';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col w-full ">
            <main className="flex-1 ">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
